### ISSUE TITLE
Error when used on Windows 7 unless recompiled.

### ISSUE THREAD

**Issue by corylulu** [Ilshidur/LoL-item-sets#1]
When running the compiled app on Windows 7, I get the following error:

Unable to cast COM object of type 'Shell32.ShellClass' to interface type 'Shell32.IShellDispatch6'. This operation failted because the QueryInterface call on the COM component for the interface with IID '{tl;dt IID}' failed due to the following error: No such interface supported

However, if I download source and compile it, it works fine.

**Comment by Ilshidur** [comment]
Yes, this is a compilation issue. I'm looking for a way to compile it from Windows 8.1 (my current OS).
But you'll get soon a fixed app', I promise !

Thanks for your feedback !

EDIT : Thanks to your pull request, the bug is fixed. Closing the issue.
