### ISSUE TITLE
Won't launch and creates error document

### ISSUE THREAD

**Issue by ZebraToucan** [Ilshidur/LoL-item-sets#12]
I unzipped the folder and ran as admin, but nothing opens and instead a new document is made called 'errors' which is empty (0kb too). 

I have Windows 10

**Comment by Ilshidur** [comment]
Thank you for your report.
Do you have installed the [.NET Framework 4.5](https://www.microsoft.com/en-US/download/details.aspx?id=30653) ?
Do you have all the required `.dll` files in the same directory as the application ? There is 8 of them.

**Comment by ZebraToucan** [comment]
The instillation client said that I do have .NET Framework 4.5 
And yes, all 8 .dll files are present and in the same location.

**Comment by Ilshidur** [comment]
It seems weird.
Have you renamed the application by any chance ?

**Comment by xKeiro** [comment]
I have the exact same issue, and I didn't rename the application.

**Comment by ZebraToucan** [comment]
I tried to rename it, adding underscores instead of spaces. Continued with the same problem.

**Comment by Ilshidur** [comment]
I'm sorry this happens to you guys. Maybe you can try to run the application using the compatibility mode for Windows 7 ?
Also, as the app retrieves some datas to the server when opening, it can fail to run if your Internet is down.

**Comment by ZebraToucan** [comment]
Tried running it using Windows 7 compatibility mode, the same problem occurs. I'm connected via ethernet so I know my connection hasn't been an issue.

**Comment by Ilshidur** [comment]
@ZebraToucan @xKeiro Have you always faced this issue or the application suddenly stopped working ?

**Comment by scmanjarrez** [comment]
It suddenly stopped working, I've been using the same executable for 1 year without problems. @Ilshidur

**Comment by ZebraToucan** [comment]
@Ilshidur That was the first time downloaded/tried to use it

**Comment by xKeiro** [comment]
It was the first time trying to use the program as well.

**Comment by Ilshidur** [comment]
I figured out the issue and will release a new version soon.

**Comment by Ilshidur** [comment]
Just published the [new version](https://github.com/league-of-legends-devs/LoL-item-sets/releases/tag/0.3.0.1) on the website and it's now available.

Tell me if this fixed your problem ;-)

**Comment by scmanjarrez** [comment]
It works flawlessly, thank you so much  😄 
PS: Just curiosity, what was the problem?

**Comment by Ilshidur** [comment]
I don't really know where the problem suddenly came from. The issue was "Could not create SSL/TLS secure channel". Surprisingly, my TLS certificates weren't outdated, so I just googled the error and copy/pasted the first solution that came to me to the source code.
I guess Windows had an update that broke the application somehow ? We'll never know :D

**Comment by xKeiro** [comment]
![2017-09-26_00-00-22_explorer](https://user-images.githubusercontent.com/7066695/30833072-c953132e-a24d-11e7-9267-b3658f895663.png)

Sadly it didn't work for me. (yes I downloaded the version you linked)
Edit: Ok, I did nothing but tried to open it again, now it works. So there may be still some minor bug.

**Comment by Ilshidur** [comment]
@xKeiro This is weird.
I guess you're running on Windows 10 ?

**Comment by xKeiro** [comment]
Yes
