### ISSUE TITLE
How can I revert the changes that this program made?

### ISSUE THREAD

**Issue by OzanKurt** [Ilshidur/LoL-item-sets#13]
How can I revert the changes that this program made?

**Comment by Ilshidur** [comment]
Hello. At the moment, there is no automatic way to remove the installed item sets.

You can manually delete the item sets. They are located in the `Champions` folder. The path is usually this one : `C:\Riot Games\League of Legends\Config\Champions` (on Windows).

**Comment by OzanKurt** [comment]
Cool, Thanks!
