### ISSUE TITLE
Some Champions are Missing

### ISSUE THREAD

**Issue by Dakoats** [Ilshidur/LoL-item-sets#14]
I'm not entirely sure if this is an issue with connecting to the API or not, but about a dozen or so champions are missing when generating item sets. Example here [https://imgur.com/OBp3X6F](url)
Going to [https://lol-item-sets-generator.org/sets](url) shows that, as of right now, these champions are also missing from the list. [https://imgur.com/UcJrEkf](url)

**Comment by Ilshidur** [comment]
Thank you for your report.

The item sets are generated from the [champion.gg](http://champion.gg) datas (they provide a public API).
Apparently, these datas currently omit some champions (like Aatrox, for example).

I think there is not much I can do, except wait for the next build generations (every day at 12 AM) until it gets fixed.

Feel free to re-open this issue if you consider that the issue persists for too long :)

**Comment by Ilshidur** [comment]
Just bumping this post to notify that [this bug is fixed](https://github.com/league-of-legends-devs/LoL-item-sets/issues/16#issuecomment-394325271).
