### ISSUE TITLE
item sets not available on Howling Abyss

### ISSUE THREAD

**Issue by eyegouch** [Ilshidur/LoL-item-sets#15]
after getting the updated item sets yesterday, i have none of them in arams anymore (for wich im liking the sets the most)

-on Summoner's Rift all item sets are available (recommended, generated and my own)
-on Howyling Abyss only the recommended and my own are available

tried different champs (not all, but i'm pretty sure it is champion independent)
-reinstalled the Generator
-tried repairing the launcher
-reinstalled LoL completely

**Comment by Ilshidur** [comment]
Hello and thank you for our bug report.

This seems like this bug has appeared because of a [recent change in the generator](https://github.com/league-of-legends-devs/feeder.lol-item-sets-generator.org/issues/34).

I'm on the case and will fix fix as soon as possible.

**Comment by Ilshidur** [comment]
**Fixed**

Sorry but I currently don't have a Windows environment to test the fix.
Let me know if this works so I can close this issue.

**Comment by eyegouch** [comment]
tried 3 champs, all maps... seems its fixed! nice work!!

**Comment by Ilshidur** [comment]
Excellent !
Feel free to report any problem or suggestions ;-)

Closing the issue now.
